config/routes.rb
Rails.application.routes.draw do
  root 'home#top'

  get 'top' => 'home#top'
  get 'first' => 'home#first'
  get 'news' => 'home#news'
  get 'info' => 'home#info'
  get 'calender' => 'home#calender'
  get 'map' => 'home#map'
  get 'search' => 'home#search'

  get 'articles' => 'articles#top'
  get 'articles/index' => 'articles#index'
  get 'articles/first' => 'articles#first'
  get 'articles/news' => 'articles#news'
  get 'articles/info' => 'articles#info'
  get 'articles/calender' => 'articles#calender'
  get 'articles/map' => 'articles#map'
  get 'articles/search' => 'articles#search'

  get 'la' => 'la#top'
  get 'la/top' => 'la#top'
  get 'la/first' => 'la#first'
  get 'la/news' => 'la#news'
  get 'la/info' => 'la#info'
  get 'la/calender' => 'la#calender'
  get 'la/map' => 'la#map'
  get 'la/search' => 'la#search'

  get 'others' => 'others#top'
  get 'others/top'
  #get 'others/first'
  #get 'others/news'
  get 'others/info'
  #get 'others/calender'
  get 'others/map'
  #get 'others/search'
  get 'others/contact'
  get 'others/privacy-policy' => 'others#privacy_policy'
  get 'others/disclaimer'

  devise_for :users
  resources :articles
  resources :las
  # get 'help' => 'welcome#help'
  # post 'articles/:id' => 'articles#show'
  post 'articles/attach', to: 'articles#attach'
  as :user do
    get 'wusers/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'wusers' => 'devise/registrations#update', :as => 'user_registration'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    mount_uploader :image, ImagesUploader
    acts_as_taggable
    acts_as_taggable_on :skills, :interests
end

app/models/attachment.rb
class Attachment < ApplicationRecord
    has_one_attached :image
    def image_compressed
        if image.attached?
          image.variant(resize_to_fit: [700, 600]).processed
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    skip_before_action :verify_authenticity_token
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all.order(created_at: :desc)
    @tags = Article.tag_counts_on(:tags).order('count DESC')
    # @tags = Article.tag_counts_on(:tags).order('count DESC')     # 全タグ(Postモデルからtagsカラムを降順で取得)
    if 
      @tag = params[:tag]   # タグ検索用
      @article = Article.tagged_with(params[:tag])   # タグに紐付く投稿
    end
  end

  def top
    @new_article = Article.all.order(created_at: :desc).limit(4)
    @minecraft = Article.tagged_with('minecraft').limit(4)
    @aviutl = Article.tagged_with('aviutl').limit(4)
    @web = Article.tagged_with('web').limit(4)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @articles = Article.find(params[:id])
    @tags = @articles.tag_counts_on(:tags)
  end

  def first
  end

  def news
  end

  def info
  end

  def calender
  end

  def map
  end

  def search
    @articles = Article.all.order(created_at: :desc)
    @tags = Article.tag_counts_on(:tags).order('count DESC')
    # @tags = Article.tag_counts_on(:tags).order('count DESC')     # 全タグ(Postモデルからtagsカラムを降順で取得)
    if 
      @tag = params[:tag]   # タグ検索用
      @article = Article.tagged_with(params[:tag])   # タグに紐付く投稿
    end
  end

  # GET /articles/new
  def new
    @article = Article.new
    @tags = Article.tag_counts_on(:tags)
  end

  # GET /articles/1/edit
  def edit
    @tags = Article.tag_counts_on(:tags)
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def attach
    attachment = Attachment.create! image: params[:image]
    render json: { filename: url_for(attachment.image) }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:image, :title, :subtitle, :content, :tag_list)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    if 
      @news = Article.tagged_with('news').limit(3)  # タグに紐付く投稿
      @la_news = Article.tagged_with('la_news').limit(3)  # タグに紐付く投稿
      # @lainfo = MineStat.new("192.168.0.8")
    end
  end

  def first
  end

  def news
    @news = Article.tagged_with('news')
  end

  def info
  end

  def calender
  end

  def map
  end

  def search
  end
end

app/controllers/la_controller.rb
class LaController < ApplicationController
  def top
    @ms = MineStat.new("192.168.0.8")
    # <%= @ms.json_data %><%= @ms.protocol %><%= @ms.query_type %>
  end

  def first
  end

  def news
  end

  def info
  end

  def calender
  end

  def map
  end

  def search
  end
end

app/controllers/others_controller.rb
class OthersController < ApplicationController
  def top
  end

  def info
  end

  def map
  end

  def contact
  end

  def privacy_policy
  end

  def disclaimer
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    # マークダウン形式で記入するためにrequire
  require "redcarpet"
  require "coderay"

  class HTMLwithCoderay < Redcarpet::Render::HTML
    def block_code(code, language)
        language = language.split(':')[0]

        case language.to_s
        when 'rb'
            lang = 'ruby'
        when 'yml'
            lang = 'yaml'
        when 'css'
            lang = 'css'
        when 'html'
            lang = 'html'
        when ''
            lang = 'md'
        else
            lang = language
        end

        CodeRay.scan(code, lang).div
    end
  end

  # マークダウンを可能にするメソッド
  def markdown(text)
    html_render = HTMLwithCoderay.new(filter_html: true, hard_wrap: true)
    options = {
        autolink: true,
        space_after_headers: true,
        no_intra_emphasis: true,
        fenced_code_blocks: true,
        tables: true,
        hard_wrap: true,
        xhtml: true,
        lax_html_blocks: true,
        strikethrough: true
    }
    markdown = Redcarpet::Markdown.new(html_render, options)
    markdown.render(text)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/la_helper.rb
module LaHelper
end

app/helpers/others_helper.rb
module OthersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<% provide(:meta, "") %>
<% provide(:robots, "index,follow") %>
<% provide(:url, "/articles/index") %>
<% provide(:type, "website") %>
<% provide(:card, "summary_large_image") %>
<% provide(:twitter_site, "@sorata_toll") %>
<% provide(:twitter_creater, "@sorata_toll") %>
<% provide(:smn, "/assets/la/splatoon.png") %>
<% provide(:title, "ブログ一覧") %>
<% provide(:subtitle, "記事の一覧です。ブログを書いています。") %>
<% provide(:tag, "ブログ, blog") %>
<% provide(:blog, "current") %>
<% provide(:index, "current") %>
<main>
  <div class="maincol">
    <div class="main-content">
      <h1>記事の一覧</h1>
      <% @articles.each do |article| %>
        <%= link_to(article, {class: "article-a"}) do %>
          <div class="article">
            <div class="article-img">
              <%= image_tag article.image_url(:content) if article.image.present? %>
            </div>
            <div class="article-about">
              <h6><%= article.title %></h6>
              <p class="time-tag">
                <span class="time"><%= l article.created_at, format: :index %></span>
                <span class="tag"><%= article.tag_list %></span>
              </p>
              <div class="article-text">
                <p><%= article.subtitle %></p>
              </div>
            </div>
            <% if user_signed_in? %>
              <%= link_to 'Edit', edit_article_path(article) %>
              <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </div>
        <% end %>
      <% end %>
      <% if user_signed_in? %><%= link_to '記事を作成', new_article_path %><% end %>
    </div>
  </div>
</main>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/search.html.erb
<% provide(:title, "検索") %>
<% provide(:subtitle, "タグから検索します") %>
<% provide(:tag, "タグ一覧") %>
<% provide(:blog, "current") %>
<% provide(:search, "current") %>
<main>
  <div class="maincol">
    <div class="main-content">
      <h1>タグから検索</h1>
      <% if @article.present? %>
        <h2>該当記事</h2>
        <% @article.each do |article| %>
          <%= link_to(article, {class: "article-a"}) do %>
            <div class="article">
              <div class="article-img">
                <%= image_tag article.image_url(:content) if article.image.present? %>
              </div>
              <div class="article-about">
                <h6><%= article.title %></h6>
                <p class="time-tag">
                  <span class="time"><%= l article.created_at, format: :index %></span>
                  <span class="tag"><%= article.tag_list %></span>
                </p>
                <div class="article-text">
                  <p><%= article.subtitle %></p>
                </div>
              </div>
              <% if user_signed_in? %>
                <%= link_to 'Edit', edit_article_path(article) %>
                <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
            </div>
          <% end %>
        <% end %>
      <% end %>
      <h2>タグ一覧</h2>
      <h4>クリックで絞り込み</h4><br/>
      <p>
        <% @tags.each do |tag| %>
          <%= link_to "#{tag.name}(#{tag.taggings_count})", articles_search_url(tag: tag.name) %>
          <br/>
        <% end %>
        <br>
        <%= link_to 'ホームへ', root_path %>
        <% if user_signed_in? %><%= link_to '記事を作成', new_article_path %><% end %>
      </p>
    </div>
    <div class="sub-content">
      <% if @article.present? %>
        <h2>タグ一覧</h2>
        <p><% @tags.each do |tag| %>
          <%= link_to "#{tag.name}(#{tag.taggings_count})", articles_search_url(tag: tag.name) %>
          <br/>
        <% end %></p>
      <% else %>
        <h2>タグ検索</h2>
        <p>タグ検索ができます！！</p>
      <% end %>
    </div>
  </div>
</main>

app/views/articles/show.html.erb
<% @id = @article.id %>
<% provide(:meta, "") %>
<% provide(:robots, "index,follow") %>
<% provide(:url, "/articles/#@id" ) %>
<% provide(:type, "article") %>
<% provide(:card, "summary_large_image") %>
<% provide(:twitter_site, "@sorata_toll") %>
<% provide(:twitter_creater, "@sorata_toll") %>
<% provide(:smn, @article.image_url(:content)) %>
<% provide(:title, @article.title) %>
<% provide(:subtitle, @article.subtitle) %>
<% provide(:tag, @article.tag_list) %>
<% provide(:blog, "current") %>
<% provide(:top, "") %>

<div class="blog-article entry-content">
<main>
  <div class="main-content">
    <span class="time"><%= l @article.created_at %></span>
    <span class="update"><%= l @article.updated_at %></span>
    <br/>
    <div class="tag-link">
    <% @article.tag_list.each do |tag| %>
      <a href="/articles/search?tag=">
      <%= link_to articles_search_url(tag: tag) do %>
      <span class="tags"><%= tag %></span>
      <% end %>
    <% end %>
    </div>
    <h6><%= @article.title %></h6>
    <div class="smn">
      <%= image_tag @article.image_url(:content) if @article.image.present? %>
    </div>
    <p><%= @article.subtitle %></p>
    <div class="mkj">
      <div id="toc">
      </div>
    </div>
      <%= markdown(@article.content).html_safe %>

<script>

</script>

    <p><%= @article.id %>記事目でした。</p>
    <% if user_signed_in? %>
    <%= link_to 'Edit', edit_article_path(@article) %> |
    <% end %>
    <%= link_to '戻る', articles_path %>
  </div>
</main>
</div>

app/views/articles/top.html.erb
<% provide(:meta, "") %>
<% provide(:robots, "index,follow") %>
<% provide(:url, "/articles") %>
<% provide(:type, "website") %>
<% provide(:card, "summary_large_image") %>
<% provide(:twitter_site, "@sorata_toll") %>
<% provide(:twitter_creater, "@sorata_toll") %>
<% provide(:smn, "/assets/la/splatoon.png") %>
<% provide(:title, "ブログTOP") %>
<% provide(:subtitle, "おすすめ記事です。ブログを書いています。") %>
<% provide(:tag, "ブログ, blog") %>
<% provide(:blog, "current") %>
<% provide(:top, "current") %>
<main>
  <div class="maincol">
    <div class="main-content">
      <h1>ブログ</h1>
      <h2>最新の記事</h2>
        <% if @new_article.present? %>
        <% @new_article.each do |article| %>
        <%= link_to(article, {class: "article-a"}) do %>
        <div class="article">
        <div class="article-img">
        <%= image_tag article.image_url(:content) if article.image.present? %>
        </div>
        <div class="article-about">
        <h6><%= article.title %></h6>
        <p class="time-tag">
        <span class="time"><%= l article.created_at, format: :index %></span>
        <span class="tag"><%= article.tag_list %></span>
        </p>
        <div class="article-text">
        <p><%= article.subtitle %></p>
        </div>
        </div>
        <% if user_signed_in? %>
        <%= link_to 'Edit', edit_article_path(article) %>
        <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
        </div>
        <% end %>
        <% end %>
      　<% end %>
        <p><a href="/articles/index">もっと見る</a></p>
        <h1>おすすめの記事</h1>
        <h2>マイクラ #minecraft</h2>
        <% if @minecraft.present? %>
          <% @minecraft.each do |article| %>
            <%= link_to(article, {class: "article-a"}) do %>
              <div class="article">
                <div class="article-img">
                  <%= image_tag article.image_url(:content) if article.image.present? %>
                </div>
                <div class="article-about">
                  <h6><%= article.title %></h6>
                  <p class="time-tag">
                    <span class="time"><%= l article.created_at, format: :index %></span>
                    <span class="tag"><%= article.tag_list %></span>
                  </p>
                  <div class="article-text">
                      <p><%= article.subtitle %></p>
                  </div>
                </div>
                <% if user_signed_in? %>
                  <%= link_to 'Edit', edit_article_path(article) %>
                  <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %>
                <% end %>
              </div>
            <% end %>
          <% end %>
        <% end %>
        <h2>AviUtl #aviutl</h2>
        <% if @aviutl.present? %>
          <% @aviutl.each do |article| %>
            <%= link_to(article, {class: "article-a"}) do %>
              <div class="article">
                <div class="article-img">
                  <%= image_tag article.image_url(:content) if article.image.present? %>
                </div>
                <div class="article-about">
                  <h6><%= article.title %></h6>
                  <p class="time-tag">
                    <span class="time"><%= l article.created_at, format: :index %></span>
                    <span class="tag"><%= article.tag_list %></span>
                  </p>
                  <div class="article-text">
                      <p><%= article.subtitle %></p>
                  </div>
                </div>
                <% if user_signed_in? %>
                  <%= link_to 'Edit', edit_article_path(article) %>
                  <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %>
                <% end %>
              </div>
            <% end %>
          <% end %>
        <% end %>
        <h2>WEB制作 #web</h2>
        <% if @web.present? %>
          <% @web.each do |article| %>
            <%= link_to(article, {class: "article-a"}) do %>
              <div class="article">
                <div class="article-img">
                  <%= image_tag article.image_url(:content) if article.image.present? %>
                </div>
                <div class="article-about">
                  <h6><%= article.title %></h6>
                  <p class="time-tag">
                    <span class="time"><%= l article.created_at, format: :index %></span>
                    <span class="tag"><%= article.tag_list %></span>
                  </p>
                  <div class="article-text">
                      <p><%= article.subtitle %></p>
                  </div>
                </div>
                <% if user_signed_in? %>
                  <%= link_to 'Edit', edit_article_path(article) %>
                  <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %>
                <% end %>
              </div>
            <% end %>
          <% end %>
        <% end %>
    </div>
  </div>
</main>

app/views/home/top.html.erb
<% provide(:meta, "") %>
<% provide(:robots, "index,follow") %>
<% provide(:url, "") %>
<% provide(:type, "website") %>
<% provide(:card, "summary_large_image") %>
<% provide(:twitter_site, "@sorata_toll") %>
<% provide(:twitter_creater, "@sorata_toll") %>
<% provide(:smn, "/assets/la/splatoon.png") %>
<% provide(:title, "トップ") %>
<% provide(:subtitle, "Amiverse.netのトップページです。") %>
<% provide(:tag, "top, home") %>
<% provide(:home, "current") %>
<% provide(:top, "current") %>
<main>
  <div class="maincol">
    <div class="main-content">
      <h1>ようこそAmiverseへ</h1>
      <h2>ブログ</h2>
      <h3>ブログを開始しました！！</h3>
      <p>
        現在公開テスト中です。不具合があれば連絡お願いします。<br/><br/>
        横幅281px以上(GalaxyFoldはギリ無理くらい)の最新chromeブラウザでの動作は保障します。<br/><br/>
        <%= link_to 'ブログ一覧', articles_path %>
      </p><br/>
      <h2>最新のニュース #news</h2>
      <% if @news.present? %>
        <% @news.each do |article| %>
          <%= link_to(article, {class: "article-a"}) do %>
            <div class="article">
              <div class="article-img">
                <%= image_tag article.image_url(:content) if article.image.present? %>
              </div>
              <div class="article-about">
                <h6><%= article.title %></h6>
                <p class="time-tag">
                  <span class="time"><%= l article.created_at, format: :index %></span>
                  <span class="tag"><%= article.tag_list %></span>
                </p>
                <div class="article-text">
                    <p><%= article.subtitle %></p>
                </div>
              </div>
              <% if user_signed_in? %>
                <%= link_to 'Edit', edit_article_path(article) %>
                <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
            </div>
          <% end %>
        <% end %>
      <% end %>
      <h2>LA鯖のニュース #la_news</h2>
      <p>現在のサーバー状態は<a href="/la">こちら</a>から確認出来ます。</p>
      <% if @la_news.present? %>
        <% @la_news.each do |article| %>
          <%= link_to(article, {class: "article-a"}) do %>
            <div class="article">
              <div class="article-img">
                <%= image_tag article.image_url(:content) if article.image.present? %>
              </div>
              <div class="article-about">
                <h6><%= article.title %></h6>
                <p class="time-tag">
                  <span class="time"><%= l article.created_at, format: :index %></span>
                  <span class="tag"><%= article.tag_list %></span>
                </p>
                <div class="article-text">
                    <p><%= article.subtitle %></p>
                </div>
              </div>
              <% if user_signed_in? %>
                <%= link_to 'Edit', edit_article_path(article) %>
                <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <div class="sub-content">
      <div class="sub-container">
        <h1>サブコンテンツ</h1>
        <div class="youtube-scarlia">
            <div class="y-movie">
              動画見て
              <iframe width="100%" height="auto" src="https://www.youtube.com/embed/TiW7ytbvIC4" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
            <div class="y-movie">
              こっちも
              <iframe width="100%" height="auto" src="https://www.youtube.com/embed/s8vTBLwVFuI" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
        </div>
        <div class="twitter-st">
            フォローして
            <a href="https://twitter.com/sorata_toll?ref_src=twsrc%5Etfw" class="twitter-follow-button" data-show-count="false">Follow @sorata_toll</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
            <br />
            連絡など
            <a href="https://twitter.com/intent/tweet?screen_name=sorata_toll&ref_src=twsrc%5Etfw" class="twitter-mention-button" data-show-count="false">Tweet to @sorata_toll</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
            <a class="twitter-timeline" data-lang="ja" data-height="300" data-theme="dark" href="https://twitter.com/sorata_toll?ref_src=twsrc%5Etfw">Tweets by sorata_toll</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/users/_nav.erb
    <nav>
      <div class="nav-list">
        <ul>
          <a href="<%= top_path %>" style="color: #3EE7EA;" class="<%= yield(:top) %> list-5">
            <li>
              <%= image_tag "nav-list/top.svg", :width => "47", :height => "47"  %><br/>TOP
            </li>
          </a>
          <a href="<%= first_path %>" style="color: #FFAC38;" class="<%= yield(:first) %> list-6">
            <li>
              <%= image_tag "nav-list/first.svg", :width => "43", :height => "43"  %><br/>初めての方へ
            </li>
          </a>
          <a href="<%= news_path %>" style="color: #6093FB;" class="<%= yield(:news) %> list-7">
            <li>
              <%= image_tag "nav-list/news.svg", :width => "43", :height => "43"  %><br/>最新情報
            </li>
          </a>
          <a href="<%= info_path %>" style="color: #FF7284;" class="<%= yield(:info) %> list-8">
            <li>
              <%= image_tag "nav-list/info.svg", :width => "43", :height => "43"  %><br/>運営情報
            </li>
          </a>
          <a href="<%= calender_path %>" style="color: #7ACC2B;" class="<%= yield(:calender) %> list-9">
            <li>
              <%= image_tag "nav-list/calendar.svg", :width => "43", :height => "43"  %><br/>カレンダー
            </li>
          </a>
          <a href="<%= map_path %>" style="color: #BA68FF;" class="<%= yield(:map) %> list-10">
            <li>
              <%= image_tag "nav-list/map.svg", :width => "43", :height => "43"  %><br/>マップ
            </li>
          </a>
          <a href="<%= search_path %>" style="color: #FF70BF;" class="<%= yield(:search) %> list-11">
            <li>
              <%= image_tag "nav-list/search.svg", :width => "43", :height => "43"  %><br/>検索
            </li>
          </a>
        </ul>
      </div>
    </nav>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/welcome/index.html.erb
<% provide(:title, "Home") %>
<% provide(:home, "current") %>
<br>
<p id="notice"><%= notice %></p>
<h1>ようこそAmiverseへ</h1>
<p>現在βテスト中です。不具合があれば連絡お願いします。</p>
<p>横幅281px以上の最新chromeブラウザでの動作は保障します。</p>
<%= link_to 'ブログ一覧', articles_path %>
<%= link_to 'webマップ(dynmap)', 'http://amiverse.net/dynmap' %>
<%= link_to 'webマップ(bluemap)', 'http://amiverse.net/bluemap' %>

 <br/>
<iframe src="https://mc.erinn.biz/intl/polling.html.php?server_addr=amiverse.net" style="width:80%;height:60px;border:none;"></iframe>
<br/>
<a href="http://tt0.link/minecraft/"><img src="http://tt0.link/minecraft/others/servercheck/img/default.php?ip=amiverse.net&port=25565" style="width:80%;"></a>
<br/>
<a href="https://minecraft.jp/servers/amiverse.net"><img src="https://minecraft.jp/servers/amiverse.net/banner/2/560x95.png" style="width:80%;"/></a>
<br/>

<% if user_signed_in? %>
  <%= link_to 'プロフィール変更', edit_user_registration_path %>
  <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
<% else %>
  
  <%= link_to 'ログイン', new_user_session_path %>
<% end %>